/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.FrameNhanVien;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameMenu extends javax.swing.JFrame {
    private String strMaNV,strTenNV,strChucVu;
    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }
    public FrameMenu(String strMaNV,String strTenNV,String strChucVu) {
        initComponents();
        this.strMaNV=strMaNV;
        this.strTenNV=strTenNV;
        this.strChucVu=strChucVu;
        lbl_TenNhanVien2.setText(strTenNV);
        lbl_ChucVu2.setText(strChucVu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_FrameMenu = new javax.swing.JPanel();
        sp_Menu = new javax.swing.JScrollPane();
        pn_Menu = new javax.swing.JPanel();
        lbl_MenuBanHang = new javax.swing.JLabel();
        lbl_NhapHang = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_KhahcHang = new javax.swing.JLabel();
        lbl_Mon = new javax.swing.JLabel();
        lbl_Kho = new javax.swing.JLabel();
        lbl_QuanLyLuong = new javax.swing.JLabel();
        lbl_ChucVu = new javax.swing.JLabel();
        lbl_QLKhuyenMai = new javax.swing.JLabel();
        lbl_NhaCungCap = new javax.swing.JLabel();
        lbl_UuDaiThanhVien = new javax.swing.JLabel();
        lbl_QLCaLam = new javax.swing.JLabel();
        lbl_ThongKe = new javax.swing.JLabel();
        lbl_Close = new javax.swing.JLabel();
        lbl_Hiden = new javax.swing.JLabel();
        lbl_Header = new javax.swing.JLabel();
        lbl_TenNhanVien1 = new javax.swing.JLabel();
        lbl_TenNhanVien2 = new javax.swing.JLabel();
        lbl_ChucVu1 = new javax.swing.JLabel();
        lbl_ChucVu2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý cà phê");
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1050));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1050));
        setUndecorated(true);

        pn_FrameMenu.setBackground(new java.awt.Color(255, 255, 255));
        pn_FrameMenu.setLayout(null);

        sp_Menu.setBackground(new java.awt.Color(255, 255, 255));
        sp_Menu.setBorder(null);
        sp_Menu.setToolTipText("");

        pn_Menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_Menu.setPreferredSize(new java.awt.Dimension(1801, 1000));
        pn_Menu.setLayout(null);

        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang1.jpg"))); // NOI18N
        lbl_MenuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_MenuBanHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_MenuBanHang);
        lbl_MenuBanHang.setBounds(0, 0, 400, 203);

        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang1.jpg"))); // NOI18N
        lbl_NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhapHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_NhapHang);
        lbl_NhapHang.setBounds(464, 0, 400, 200);

        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien1.jpg"))); // NOI18N
        lbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhanVienMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_NhanVien);
        lbl_NhanVien.setBounds(928, 0, 400, 200);

        lbl_KhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang1.jpg"))); // NOI18N
        lbl_KhahcHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhahcHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_KhahcHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_KhahcHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_KhahcHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_KhahcHangMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_KhahcHang);
        lbl_KhahcHang.setBounds(1392, 0, 400, 200);

        lbl_Mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon1.jpg"))); // NOI18N
        lbl_Mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_MonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_MonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_MonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_MonMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_Mon);
        lbl_Mon.setBounds(0, 230, 400, 200);

        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho1.jpg"))); // NOI18N
        lbl_Kho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_KhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_KhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_KhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_KhoMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_Kho);
        lbl_Kho.setBounds(464, 230, 400, 200);

        lbl_QuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong1.jpg"))); // NOI18N
        lbl_QuanLyLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_QuanLyLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_QuanLyLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_QuanLyLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_QuanLyLuongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_QuanLyLuongMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_QuanLyLuong);
        lbl_QuanLyLuong.setBounds(1392, 230, 400, 200);

        lbl_ChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu1.jpg"))); // NOI18N
        lbl_ChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ChucVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ChucVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ChucVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ChucVuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_ChucVuMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_ChucVu);
        lbl_ChucVu.setBounds(928, 230, 400, 200);

        lbl_QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai1.jpg"))); // NOI18N
        lbl_QLKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_QLKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_QLKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_QLKhuyenMaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_QLKhuyenMaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_QLKhuyenMaiMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_QLKhuyenMai);
        lbl_QLKhuyenMai.setBounds(0, 460, 400, 200);

        lbl_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap1.jpg"))); // NOI18N
        lbl_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhaCungCapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhaCungCapMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_NhaCungCap);
        lbl_NhaCungCap.setBounds(464, 460, 400, 200);

        lbl_UuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien1.jpg"))); // NOI18N
        lbl_UuDaiThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_UuDaiThanhVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_UuDaiThanhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_UuDaiThanhVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_UuDaiThanhVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_UuDaiThanhVienMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_UuDaiThanhVien);
        lbl_UuDaiThanhVien.setBounds(928, 460, 400, 200);

        lbl_QLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam1.jpg"))); // NOI18N
        lbl_QLCaLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_QLCaLamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_QLCaLamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_QLCaLamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_QLCaLamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_QLCaLamMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_QLCaLam);
        lbl_QLCaLam.setBounds(1392, 460, 400, 200);

        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke1.jpg"))); // NOI18N
        lbl_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_ThongKeMouseReleased(evt);
            }
        });
        pn_Menu.add(lbl_ThongKe);
        lbl_ThongKe.setBounds(0, 690, 400, 200);

        sp_Menu.setViewportView(pn_Menu);

        pn_FrameMenu.add(sp_Menu);
        sp_Menu.setBounds(50, 400, 1820, 600);

        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/close1.png"))); // NOI18N
        lbl_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_CloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_CloseMouseReleased(evt);
            }
        });
        pn_FrameMenu.add(lbl_Close);
        lbl_Close.setBounds(1880, 5, 40, 40);

        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frame/an1.png"))); // NOI18N
        lbl_Hiden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HidenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_HidenMouseReleased(evt);
            }
        });
        pn_FrameMenu.add(lbl_Hiden);
        lbl_Hiden.setBounds(1835, 5, 40, 40);

        lbl_Header.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Header.setOpaque(true);
        pn_FrameMenu.add(lbl_Header);
        lbl_Header.setBounds(0, 0, 1920, 50);

        lbl_TenNhanVien1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_TenNhanVien1.setText("Tên nhân viên:");
        pn_FrameMenu.add(lbl_TenNhanVien1);
        lbl_TenNhanVien1.setBounds(120, 120, 230, 60);

        lbl_TenNhanVien2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pn_FrameMenu.add(lbl_TenNhanVien2);
        lbl_TenNhanVien2.setBounds(360, 120, 500, 60);

        lbl_ChucVu1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_ChucVu1.setText("Chức vụ:");
        pn_FrameMenu.add(lbl_ChucVu1);
        lbl_ChucVu1.setBounds(120, 190, 150, 60);

        lbl_ChucVu2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        pn_FrameMenu.add(lbl_ChucVu2);
        lbl_ChucVu2.setBounds(270, 190, 300, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_FrameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_FrameMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1920, 1050);
    }// </editor-fold>//GEN-END:initComponents
    
    //Icon để setIcon khi hover vào menu bán hàng 
    private void lbl_MenuBanHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseReleased
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseReleased

    private void lbl_MenuBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMousePressed
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMousePressed

    private void lbl_MenuBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseEntered
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseEntered

    private void lbl_MenuBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseExited
        lbl_MenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/menubanhang1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_MenuBanHangMouseExited

    private void lbl_MenuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MenuBanHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_MenuBanHangMouseClicked
    
   
    //Icon để setIcon khi hover vào nhân viên
    private void lbl_NhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseReleased
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseReleased

    private void lbl_NhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMousePressed
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMousePressed

    private void lbl_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseEntered
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseEntered

    private void lbl_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseExited
        lbl_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhanvien1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhanVienMouseExited

    private void lbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhanVienMouseClicked
        try {
            FrameNhanVien s1=new FrameNhanVien();
            s1.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_NhanVienMouseClicked
    
    //Icon để setIcon khi hover vào khách hàng
    private void lbl_KhahcHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhahcHangMouseReleased
        lbl_KhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhahcHangMouseReleased

    private void lbl_KhahcHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhahcHangMousePressed
        lbl_KhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang12.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhahcHangMousePressed

    private void lbl_KhahcHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhahcHangMouseEntered
        lbl_KhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhahcHangMouseEntered

    private void lbl_KhahcHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhahcHangMouseExited
        lbl_KhahcHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khachhang1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhahcHangMouseExited

    private void lbl_KhahcHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhahcHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_KhahcHangMouseClicked
    
    //Icon để setIcon khi hover vào món
    private void lbl_MonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MonMouseReleased
        lbl_Mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_lbl_MonMouseReleased

    private void lbl_MonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MonMousePressed
        lbl_Mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_lbl_MonMousePressed

    private void lbl_MonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MonMouseEntered
        lbl_Mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon2.jpg")));// NOI18N
    }//GEN-LAST:event_lbl_MonMouseEntered

    private void lbl_MonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MonMouseExited
        lbl_Mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/Mon1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_MonMouseExited

    private void lbl_MonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_MonMouseClicked
    
    //Icon để setIcon khi hover vào kho
    private void lbl_KhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMouseReleased
        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhoMouseReleased

    private void lbl_KhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMousePressed
        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhoMousePressed

    private void lbl_KhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMouseEntered
        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhoMouseEntered

    private void lbl_KhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMouseExited
        lbl_Kho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/kho1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_KhoMouseExited

    private void lbl_KhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_KhoMouseClicked
    
    //Icon để setIcon khi hover vào nhập hàng
    private void lbl_NhapHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseReleased
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N                                   
    }//GEN-LAST:event_lbl_NhapHangMouseReleased

    private void lbl_NhapHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMousePressed
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N                                  
    }//GEN-LAST:event_lbl_NhapHangMousePressed

    private void lbl_NhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseEntered
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang2.jpg"))); // NOI18N          
    }//GEN-LAST:event_lbl_NhapHangMouseEntered

    private void lbl_NhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseExited
        lbl_NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhaphang1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapHangMouseExited

    private void lbl_NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_NhapHangMouseClicked
    
    //Icon để setIcon khi hover vào quản lý lương
    private void lbl_QuanLyLuongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QuanLyLuongMouseReleased
        lbl_QuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QuanLyLuongMouseReleased

    private void lbl_QuanLyLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QuanLyLuongMousePressed
        lbl_QuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QuanLyLuongMousePressed

    private void lbl_QuanLyLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QuanLyLuongMouseEntered
        lbl_QuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QuanLyLuongMouseEntered

    private void lbl_QuanLyLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QuanLyLuongMouseExited
        lbl_QuanLyLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlyluong1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QuanLyLuongMouseExited

    private void lbl_QuanLyLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QuanLyLuongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_QuanLyLuongMouseClicked
    
    //Icon để setIcon khi hover vào chức vụ
    private void lbl_ChucVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChucVuMouseReleased
        lbl_ChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ChucVuMouseReleased

    private void lbl_ChucVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChucVuMousePressed
        lbl_ChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ChucVuMousePressed

    private void lbl_ChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChucVuMouseEntered
        lbl_ChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ChucVuMouseEntered

    private void lbl_ChucVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChucVuMouseExited
        lbl_ChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/chucvu1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ChucVuMouseExited

    private void lbl_ChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChucVuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ChucVuMouseClicked
    
    //Icon để setIcon khi hover vào khuyến mãi
    private void lbl_QLKhuyenMaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLKhuyenMaiMouseReleased
        lbl_QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLKhuyenMaiMouseReleased

    private void lbl_QLKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLKhuyenMaiMousePressed
        lbl_QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLKhuyenMaiMousePressed

    private void lbl_QLKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLKhuyenMaiMouseEntered
        lbl_QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLKhuyenMaiMouseEntered

    private void lbl_QLKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLKhuyenMaiMouseExited
        lbl_QLKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/khuyenmai1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLKhuyenMaiMouseExited

    private void lbl_QLKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLKhuyenMaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_QLKhuyenMaiMouseClicked
    
    //Icon để setIcon khi hover vào nhà cung cấp
    private void lbl_NhaCungCapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhaCungCapMouseReleased
        lbl_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhaCungCapMouseReleased

    private void lbl_NhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhaCungCapMousePressed
        lbl_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhaCungCapMousePressed

    private void lbl_NhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhaCungCapMouseEntered
        lbl_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhaCungCapMouseEntered

    private void lbl_NhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhaCungCapMouseExited
        lbl_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/nhacungcap1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_NhaCungCapMouseExited

    private void lbl_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhaCungCapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_NhaCungCapMouseClicked
    
    //Icon để setIcon khi hover vào ưu đãi thành viên
    private void lbl_UuDaiThanhVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UuDaiThanhVienMouseReleased
        lbl_UuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_UuDaiThanhVienMouseReleased

    private void lbl_UuDaiThanhVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UuDaiThanhVienMousePressed
        lbl_UuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_UuDaiThanhVienMousePressed

    private void lbl_UuDaiThanhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UuDaiThanhVienMouseEntered
        lbl_UuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_UuDaiThanhVienMouseEntered

    private void lbl_UuDaiThanhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UuDaiThanhVienMouseExited
        lbl_UuDaiThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/uudaithanhvien1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_UuDaiThanhVienMouseExited

    private void lbl_UuDaiThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UuDaiThanhVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_UuDaiThanhVienMouseClicked
    
    //Icon để setIcon khi hover vào thống kê
    private void lbl_ThongKeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseReleased
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ThongKeMouseReleased

    private void lbl_ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMousePressed
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ThongKeMousePressed

    private void lbl_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseEntered
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ThongKeMouseEntered

    private void lbl_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseExited
        lbl_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/thongke1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_ThongKeMouseExited

    private void lbl_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ThongKeMouseClicked

    //Icon để setIcon khi hover vào ca làm
    private void lbl_QLCaLamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLCaLamMouseReleased
        lbl_QLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLCaLamMouseReleased

    private void lbl_QLCaLamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLCaLamMousePressed
        lbl_QLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLCaLamMousePressed

    private void lbl_QLCaLamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLCaLamMouseExited
        lbl_QLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam1.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLCaLamMouseExited

    private void lbl_QLCaLamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLCaLamMouseEntered
        lbl_QLCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanly/quanlycalam2.jpg"))); // NOI18N
    }//GEN-LAST:event_lbl_QLCaLamMouseEntered

    private void lbl_QLCaLamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_QLCaLamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_QLCaLamMouseClicked
    
    //Icon để setIcon khi hover vào close
    private void lbl_CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseReleased
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseReleased

    private void lbl_CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMousePressed
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMousePressed

    private void lbl_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseEntered
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseEntered

    private void lbl_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseExited
        lbl_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/close1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_CloseMouseExited

    private void lbl_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_CloseMouseClicked
    
    //Icon để setIcon khi hover vào hiden
    private void lbl_HidenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseReleased
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseReleased

    private void lbl_HidenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMousePressed
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMousePressed

    private void lbl_HidenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseEntered
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseEntered

    private void lbl_HidenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseExited
        lbl_Hiden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame/an1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HidenMouseExited

    private void lbl_HidenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HidenMouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lbl_HidenMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_ChucVu1;
    private javax.swing.JLabel lbl_ChucVu2;
    private javax.swing.JLabel lbl_Close;
    private javax.swing.JLabel lbl_Header;
    private javax.swing.JLabel lbl_Hiden;
    private javax.swing.JLabel lbl_KhahcHang;
    private javax.swing.JLabel lbl_Kho;
    private javax.swing.JLabel lbl_MenuBanHang;
    private javax.swing.JLabel lbl_Mon;
    private javax.swing.JLabel lbl_NhaCungCap;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_NhapHang;
    private javax.swing.JLabel lbl_QLCaLam;
    private javax.swing.JLabel lbl_QLKhuyenMai;
    private javax.swing.JLabel lbl_QuanLyLuong;
    private javax.swing.JLabel lbl_TenNhanVien1;
    private javax.swing.JLabel lbl_TenNhanVien2;
    private javax.swing.JLabel lbl_ThongKe;
    private javax.swing.JLabel lbl_UuDaiThanhVien;
    private javax.swing.JPanel pn_FrameMenu;
    private javax.swing.JPanel pn_Menu;
    private javax.swing.JScrollPane sp_Menu;
    // End of variables declaration//GEN-END:variables
}
