/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.NhanVienController;
import DTO.NhanVienDTO;
import static View.FrameNhanVien.arNV;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameNhanVienBiAn extends javax.swing.JFrame {
    static ArrayList<NhanVienDTO> arNV=new ArrayList<NhanVienDTO>();
    NhanVienController NhanVien = new NhanVienController();
    DefaultTableModel model;
    /**
     * Creates new form FrameNhanVienBiAn
     */
    public void LoadDuLieu() throws Exception{
        model=(DefaultTableModel) tbl_DSNhanVienAn.getModel();
        arNV.clear();
        arNV=NhanVien.LoadNhanVien();
        int i=1;
        for(NhanVienDTO nv:arNV){
            if(nv.getiTrangThai()==0){
                Vector row= new Vector();
                row.add(i++);
                row.add(nv.getStrMaNV());
                row.add(nv.getStrHoNV());
                row.add(nv.getStrTenNV());
                row.add(nv.getStrGioiTinh());
                row.add(nv.getStrChucVu());
                model.addRow(row);
            }
        }
        model.fireTableDataChanged();
    }
    
    public FrameNhanVienBiAn() throws Exception {
        initComponents();
        LoadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_DanhSachBiAn = new javax.swing.JLabel();
        sp_DSNhanVien = new javax.swing.JScrollPane();
        tbl_DSNhanVienAn = new javax.swing.JTable();
        lbl_MoAn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 100, 1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lbl_DanhSachBiAn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_DanhSachBiAn.setText("Danh sách nhân viên bị ẩn");
        jPanel1.add(lbl_DanhSachBiAn);
        lbl_DanhSachBiAn.setBounds(300, 50, 400, 40);

        tbl_DSNhanVienAn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_DSNhanVienAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Họ nhân viên", "Tên nhân viên", "Giới tính", "Chức vụ"
            }
        ));
        sp_DSNhanVien.setViewportView(tbl_DSNhanVienAn);

        jPanel1.add(sp_DSNhanVien);
        sp_DSNhanVien.setBounds(50, 150, 900, 580);

        lbl_MoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/moan1.png"))); // NOI18N
        lbl_MoAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MoAnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_MoAnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_MoAnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_MoAnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_MoAnMouseReleased(evt);
            }
        });
        jPanel1.add(lbl_MoAn);
        lbl_MoAn.setBounds(800, 50, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Set onclick lbl_MoAn
    private void lbl_MoAnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MoAnMousePressed
        lbl_MoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/moan2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MoAnMousePressed

    private void lbl_MoAnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MoAnMouseReleased
        lbl_MoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/moan2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MoAnMouseReleased

    private void lbl_MoAnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MoAnMouseEntered
        lbl_MoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/moan2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MoAnMouseEntered

    private void lbl_MoAnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MoAnMouseExited
        lbl_MoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/moan1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_MoAnMouseExited

    private void lbl_MoAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MoAnMouseClicked
        int iSelect=tbl_DSNhanVienAn.getSelectedRow();
        //Kiểm tra có chọn Row trong table không
        if(iSelect>=0){
            int input=JOptionPane.showConfirmDialog(null, "Bạn muốn mở ẩn nhân viên ?","Xác nhận",JOptionPane.YES_NO_OPTION);
            // 0=yes, 1=no
            if(input==0){
                    try {    
                        NhanVien.CapNhatTrangThai((String) model.getValueAt(iSelect, 1),"1");
                        model.removeRow(iSelect);
                        model.fireTableDataChanged();
                    } catch (Exception ex) {
                        Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
            }
        }else{
            JOptionPane.showMessageDialog(null,"Bạn chưa chọn Row.");
        }
    }//GEN-LAST:event_lbl_MoAnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNhanVienBiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNhanVienBiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNhanVienBiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNhanVienBiAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameNhanVienBiAn().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrameNhanVienBiAn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DanhSachBiAn;
    private javax.swing.JLabel lbl_MoAn;
    private javax.swing.JScrollPane sp_DSNhanVien;
    private javax.swing.JTable tbl_DSNhanVienAn;
    // End of variables declaration//GEN-END:variables
}
