/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DangNhapController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameDangNhap extends javax.swing.JFrame {
    DangNhapController DangNhap = new DangNhapController();
    /**
     * Creates new form FrameDangNhap
     */
    public FrameDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_DangNhap1 = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        lbl_DangNhap = new javax.swing.JLabel();
        lbl_NhapLai = new javax.swing.JLabel();
        lbl_AnhRight = new javax.swing.JLabel();
        lbl_AnhLeft = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        cb_HienThi = new javax.swing.JCheckBox();
        pf_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý quán cà phê");
        setBounds(new java.awt.Rectangle(570, 200, 800, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        lbl_DangNhap1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_DangNhap1.setText("Đăng nhập");
        lbl_DangNhap1.setInheritsPopupMenu(false);
        jPanel1.add(lbl_DangNhap1);
        lbl_DangNhap1.setBounds(290, 70, 224, 56);

        lbl_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/user.png"))); // NOI18N
        jPanel1.add(lbl_User);
        lbl_User.setBounds(180, 200, 50, 50);

        lbl_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/password.png"))); // NOI18N
        jPanel1.add(lbl_Password);
        lbl_Password.setBounds(180, 270, 50, 70);

        lbl_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/dangnhap.png"))); // NOI18N
        lbl_DangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_DangNhapMouseReleased(evt);
            }
        });
        jPanel1.add(lbl_DangNhap);
        lbl_DangNhap.setBounds(400, 410, 200, 50);

        lbl_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/nhaplai.png"))); // NOI18N
        lbl_NhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NhapLaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_NhapLaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_NhapLaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_NhapLaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_NhapLaiMouseReleased(evt);
            }
        });
        jPanel1.add(lbl_NhapLai);
        lbl_NhapLai.setBounds(190, 410, 200, 50);

        lbl_AnhRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/caphe.png"))); // NOI18N
        jPanel1.add(lbl_AnhRight);
        lbl_AnhRight.setBounds(570, 300, 220, 270);

        lbl_AnhLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/caphe1.png"))); // NOI18N
        jPanel1.add(lbl_AnhLeft);
        lbl_AnhLeft.setBounds(0, -20, 300, 240);

        txt_User.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_User.setText("Nhập tài khoản");
        txt_User.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_User.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.add(txt_User);
        txt_User.setBounds(240, 200, 400, 50);

        cb_HienThi.setBackground(new java.awt.Color(255, 255, 255));
        cb_HienThi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_HienThi.setText("Hiển thị mật khẩu");
        cb_HienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_HienThiActionPerformed(evt);
            }
        });
        jPanel1.add(cb_HienThi);
        cb_HienThi.setBounds(430, 350, 125, 25);

        pf_Password.setText("Password");
        pf_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(pf_Password);
        pf_Password.setBounds(240, 280, 400, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_HienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_HienThiActionPerformed
        if(cb_HienThi.isSelected()) {
            pf_Password.setEchoChar((char) 0);
        } else {
            pf_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_HienThiActionPerformed
    
    //Tạo even cho nút Đăng Nhập
    private void lbl_DangNhapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMouseReleased
        lbl_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/dangnhap1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_DangNhapMouseReleased

    private void lbl_DangNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMousePressed
        lbl_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/dangnhap1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_DangNhapMousePressed

    private void lbl_DangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMouseEntered
        lbl_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/dangnhap1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_DangNhapMouseEntered

    private void lbl_DangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMouseExited
        lbl_DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/dangnhap.png"))); // NOI18N
    }//GEN-LAST:event_lbl_DangNhapMouseExited

    private void lbl_DangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangNhapMouseClicked
        String strTaiKhoan, strMatKhau, strKetQua;
        strTaiKhoan = txt_User.getText();
        strMatKhau = pf_Password.getText();
        try {
            //System.out.println(strTaiKhoan+"-"+strMatKhau);
            strKetQua = DangNhap.DangNhapController(strTaiKhoan, strMatKhau);
            if(strKetQua=="Đăng nhập thành công"){
                setVisible(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(FrameDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbl_DangNhapMouseClicked
    
    //Tạo even cho nút Nhập lại
    private void lbl_NhapLaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapLaiMouseReleased
        lbl_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/nhaplai1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapLaiMouseReleased

    private void lbl_NhapLaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapLaiMousePressed
        lbl_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/nhaplai1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapLaiMousePressed

    private void lbl_NhapLaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapLaiMouseEntered
        lbl_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/nhaplai1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapLaiMouseEntered

    private void lbl_NhapLaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapLaiMouseExited
        lbl_NhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangnhap/nhaplai.png"))); // NOI18N
    }//GEN-LAST:event_lbl_NhapLaiMouseExited

    private void lbl_NhapLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NhapLaiMouseClicked
        txt_User.setText("Nhập tài khoản");
        pf_Password.setText("password");
    }//GEN-LAST:event_lbl_NhapLaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_HienThi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AnhLeft;
    private javax.swing.JLabel lbl_AnhRight;
    private javax.swing.JLabel lbl_DangNhap;
    private javax.swing.JLabel lbl_DangNhap1;
    private javax.swing.JLabel lbl_NhapLai;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPasswordField pf_Password;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
