/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ChucVuController;
import Controller.NhanVienController;
import DTO.ChucVuDTO;
import DTO.NhanVienDTO;
import static View.FrameThemNhanVien.arCV;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LAPTOPTOKYO
 */
public class FrameSuaNhanVien extends javax.swing.JFrame {
    //Gọi hàm để lấy mã nhân viên
    NhanVienController NhanVien = new NhanVienController();
    //Gọi hàm để lấy mã chức vụ
    ChucVuController ChucVu = new ChucVuController();
    //Mãng Chức vụ và nhân viên
    static ArrayList<NhanVienDTO> arNV=new ArrayList<NhanVienDTO>();
    static ArrayList<ChucVuDTO> arCV=new ArrayList<ChucVuDTO>();
    /**
     * Creates new form FrameSuaNhanVien
     */
    //Set Chức vụ vào combobox
    public void setChucVu() throws Exception{
        arCV=ChucVu.LoadChucVu();
        for(ChucVuDTO cv:arCV){
            //System.out.println(cv.getStrMaCV());
            //Kiểm tra nếu là Admin thì không thêm vào
            if(cv.getStrMaCV().equals("AD")){ 
            }else{
                cbb_ChucVu.addItem(cv.getStrTenCV());
            }
        }
    }
    
    //SET THÔNG TIN NHÂN VIÊN CẦN SỬA VÀO
    public void setThongTin(String strMaNV) throws Exception{
        arNV.clear();
        arNV=NhanVien.SelectNhanVien(strMaNV);
        //Set dữ liệu vào txt
        txt_MaNhanVien.setText(arNV.get(0).getStrMaNV());
        txt_HoNhanVien.setText(arNV.get(0).getStrHoNV());
        txt_TenNhanVien.setText(arNV.get(0).getStrTenNV());
        cbb_GioiTinh.setSelectedItem(arNV.get(0).getStrGioiTinh());
        //Format string thành Date với dạng yyyy-MM-dd
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(arNV.get(0).getStrNgaySinh());
        dc_NgaySinh.setDate(date);
        txt_DiaChi.setText(arNV.get(0).getStrDiaChi());
        txt_CMND.setText(arNV.get(0).getStrCMND());
        txt_SoDienThoai.setText(arNV.get(0).getStrSDT());
        for(ChucVuDTO cv:arCV){
            if(arNV.get(0).getStrChucVu().equals(cv.getStrMaCV()))
            cbb_ChucVu.setSelectedItem(cv.getStrTenCV());
        }
    }
    
    public FrameSuaNhanVien() throws Exception {
        initComponents();
        setChucVu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_ThemNhanVien = new javax.swing.JPanel();
        lbl_SuaNhanVien1 = new javax.swing.JLabel();
        lbl_MaNhanVien = new javax.swing.JLabel();
        lbl_HoNhanVien = new javax.swing.JLabel();
        lbl_TenNhanVien = new javax.swing.JLabel();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_NgaySinh = new javax.swing.JLabel();
        lbl_DiaChi = new javax.swing.JLabel();
        lbl_CMND = new javax.swing.JLabel();
        lbl_SoDienThoai = new javax.swing.JLabel();
        lbl_ChucVu = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        txt_HoNhanVien = new javax.swing.JTextField();
        txt_TenNhanVien = new javax.swing.JTextField();
        cbb_GioiTinh = new javax.swing.JComboBox<>();
        txt_DiaChi = new javax.swing.JTextField();
        txt_CMND = new javax.swing.JTextField();
        txt_SoDienThoai = new javax.swing.JTextField();
        cbb_ChucVu = new javax.swing.JComboBox<>();
        lbl_HuySua = new javax.swing.JLabel();
        lbl_SuaNhanVien = new javax.swing.JLabel();
        dc_NgaySinh = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 100, 1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));

        pn_ThemNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pn_ThemNhanVien.setLayout(null);

        lbl_SuaNhanVien1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_SuaNhanVien1.setText("Sửa nhân viên");
        pn_ThemNhanVien.add(lbl_SuaNhanVien1);
        lbl_SuaNhanVien1.setBounds(335, 50, 330, 50);

        lbl_MaNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_MaNhanVien.setText("Mã nhân viên");
        pn_ThemNhanVien.add(lbl_MaNhanVien);
        lbl_MaNhanVien.setBounds(150, 150, 150, 40);

        lbl_HoNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_HoNhanVien.setText("Họ nhân viên");
        pn_ThemNhanVien.add(lbl_HoNhanVien);
        lbl_HoNhanVien.setBounds(150, 200, 150, 40);

        lbl_TenNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_TenNhanVien.setText("Tên nhân viên");
        pn_ThemNhanVien.add(lbl_TenNhanVien);
        lbl_TenNhanVien.setBounds(150, 250, 150, 40);

        lbl_GioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_GioiTinh.setText("Giới tính");
        pn_ThemNhanVien.add(lbl_GioiTinh);
        lbl_GioiTinh.setBounds(150, 300, 150, 40);

        lbl_NgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_NgaySinh.setText("Ngày sinh");
        pn_ThemNhanVien.add(lbl_NgaySinh);
        lbl_NgaySinh.setBounds(150, 350, 150, 40);

        lbl_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_DiaChi.setText("Địa chỉ");
        pn_ThemNhanVien.add(lbl_DiaChi);
        lbl_DiaChi.setBounds(150, 400, 150, 40);

        lbl_CMND.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_CMND.setText("CMND");
        pn_ThemNhanVien.add(lbl_CMND);
        lbl_CMND.setBounds(150, 450, 150, 40);

        lbl_SoDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_SoDienThoai.setText("Số điện thoại ");
        pn_ThemNhanVien.add(lbl_SoDienThoai);
        lbl_SoDienThoai.setBounds(150, 500, 150, 40);

        lbl_ChucVu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_ChucVu.setText("Chức vụ");
        pn_ThemNhanVien.add(lbl_ChucVu);
        lbl_ChucVu.setBounds(150, 550, 150, 40);

        txt_MaNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_MaNhanVien.setFocusable(false);
        txt_MaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNhanVienActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(txt_MaNhanVien);
        txt_MaNhanVien.setBounds(300, 150, 500, 40);

        txt_HoNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_HoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HoNhanVienActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(txt_HoNhanVien);
        txt_HoNhanVien.setBounds(300, 200, 500, 40);

        txt_TenNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_TenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenNhanVienActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(txt_TenNhanVien);
        txt_TenNhanVien.setBounds(300, 250, 500, 40);

        cbb_GioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbb_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giới tính", "Nam", "Nữ" }));
        cbb_GioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_GioiTinhActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(cbb_GioiTinh);
        cbb_GioiTinh.setBounds(300, 300, 250, 40);

        txt_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiaChiActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(txt_DiaChi);
        txt_DiaChi.setBounds(300, 400, 500, 40);

        txt_CMND.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pn_ThemNhanVien.add(txt_CMND);
        txt_CMND.setBounds(300, 450, 500, 40);

        txt_SoDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_SoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoDienThoaiActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(txt_SoDienThoai);
        txt_SoDienThoai.setBounds(300, 500, 500, 40);

        cbb_ChucVu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ" }));
        cbb_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_ChucVuActionPerformed(evt);
            }
        });
        pn_ThemNhanVien.add(cbb_ChucVu);
        cbb_ChucVu.setBounds(300, 550, 250, 40);

        lbl_HuySua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framehuysua1.png"))); // NOI18N
        lbl_HuySua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HuySuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_HuySuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_HuySuaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HuySuaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_HuySuaMouseReleased(evt);
            }
        });
        pn_ThemNhanVien.add(lbl_HuySua);
        lbl_HuySua.setBounds(330, 660, 150, 50);

        lbl_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framesuanhanvien1.png"))); // NOI18N
        lbl_SuaNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SuaNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SuaNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SuaNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_SuaNhanVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_SuaNhanVienMouseReleased(evt);
            }
        });
        pn_ThemNhanVien.add(lbl_SuaNhanVien);
        lbl_SuaNhanVien.setBounds(500, 660, 150, 50);
        pn_ThemNhanVien.add(dc_NgaySinh);
        dc_NgaySinh.setBounds(300, 350, 250, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_ThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_ThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNhanVienActionPerformed

    private void txt_HoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HoNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HoNhanVienActionPerformed

    private void txt_TenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenNhanVienActionPerformed

    private void txt_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DiaChiActionPerformed

    private void txt_SoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoDienThoaiActionPerformed

    private void cbb_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_ChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_ChucVuActionPerformed
    
    //Set onclick lbl_HuySua
    private void lbl_HuySuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuySuaMouseClicked
        int input=JOptionPane.showConfirmDialog(null, "Bạn muốn hủy sửa nhân viên ?","Xác nhận",JOptionPane.YES_NO_OPTION);
        // 0=yes, 1=no
        if(input == 0){
            
        }
    }//GEN-LAST:event_lbl_HuySuaMouseClicked
    
    private void lbl_HuySuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuySuaMouseEntered
        lbl_HuySua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framehuysua2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HuySuaMouseEntered

    private void lbl_HuySuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuySuaMouseExited
        lbl_HuySua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framehuysua1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HuySuaMouseExited

    private void lbl_HuySuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuySuaMousePressed
        lbl_HuySua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framehuysua2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HuySuaMousePressed

    private void lbl_HuySuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuySuaMouseReleased
        lbl_HuySua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framehuysua2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_HuySuaMouseReleased
    
    //Set onclick lbl_ThemNhanVien
    private void lbl_SuaNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaNhanVienMouseClicked
        int input=JOptionPane.showConfirmDialog(null, "Bạn muốn sửa nhân viên ?","Xác nhận",JOptionPane.YES_NO_OPTION);
        // 0=yes, 1=no
        if(input == 0){
            Date day= new Date();
            //Format ngay ve dang yyyy-MM-dd
            DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            //Test
            //System.out.print("Nhân viên: "+txt_MaNhanVien.getText()+"/ "+txt_HoNhanVien.getText()+"/ "+txt_TenNhanVien.getText()+"/ "+cbb_GioiTinh.getSelectedItem()+"/ "+df.format(dc_NgaySinh.getDate())+"/ "+txt_DiaChi.getText()+"/ "+txt_CMND.getText()+"/ "+txt_SoDienThoai.getText()+"/ "+java.time.LocalDate.now()+"/ "+cbb_ChucVu.getSelectedItem()+"/ 0");
            Vector row=new Vector();
            row.add(txt_MaNhanVien.getText());
            row.add(txt_HoNhanVien.getText());
            row.add(txt_TenNhanVien.getText());
            row.add(cbb_GioiTinh.getSelectedItem());
            row.add(df.format(dc_NgaySinh.getDate()));
            row.add(txt_DiaChi.getText());
            row.add(txt_CMND.getText());
            row.add(txt_SoDienThoai.getText());
            row.add(java.time.LocalDate.now());
            for(ChucVuDTO cv: arCV){
                //Kiểm tra để lấy mã chức vụ
                if(cv.getStrTenCV().equals(cbb_ChucVu.getSelectedItem())){
                    System.out.print(cv.getStrMaCV());
                    row.add(cv.getStrMaCV());
                }
            }
            row.add(1);
            try {
                NhanVien.CapNhatNhanVien(row);
            } catch (Exception ex) {
                Logger.getLogger(FrameThemNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lbl_SuaNhanVienMouseClicked
    
    private void lbl_SuaNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaNhanVienMouseEntered
        lbl_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framesuanhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_SuaNhanVienMouseEntered

    private void lbl_SuaNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaNhanVienMouseExited
        lbl_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framesuanhanvien1.png"))); // NOI18N
    }//GEN-LAST:event_lbl_SuaNhanVienMouseExited

    private void lbl_SuaNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaNhanVienMousePressed
        lbl_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framesuanhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_SuaNhanVienMousePressed

    private void lbl_SuaNhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SuaNhanVienMouseReleased
        lbl_SuaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/framesuanhanvien2.png"))); // NOI18N
    }//GEN-LAST:event_lbl_SuaNhanVienMouseReleased

    private void cbb_GioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_GioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_GioiTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameSuaNhanVien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrameSuaNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb_ChucVu;
    private javax.swing.JComboBox<String> cbb_GioiTinh;
    private com.toedter.calendar.JDateChooser dc_NgaySinh;
    private javax.swing.JLabel lbl_CMND;
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_HoNhanVien;
    private javax.swing.JLabel lbl_HuySua;
    private javax.swing.JLabel lbl_MaNhanVien;
    private javax.swing.JLabel lbl_NgaySinh;
    private javax.swing.JLabel lbl_SoDienThoai;
    private javax.swing.JLabel lbl_SuaNhanVien;
    private javax.swing.JLabel lbl_SuaNhanVien1;
    private javax.swing.JLabel lbl_TenNhanVien;
    private javax.swing.JPanel pn_ThemNhanVien;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_HoNhanVien;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_TenNhanVien;
    // End of variables declaration//GEN-END:variables
}
